// <auto-generated />
namespace AlunoCurso.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class faculdade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(faculdade));
        
        string IMigrationMetadata.Id
        {
            get { return "202009282115574_faculdade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
